[package]
name = "impc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
argh = "0.1.12"
nom = "7.1.3"
num-traits = "0.2.18"
static_assertions = "1.1.0"
thiserror = "1.0.58"
