[package]
name = "impc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyerror = "0.1.12"
argh = "0.1.12"
nom = "7.1.3"
