[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
int = { version = "0.1.0", path = "../int" }
lexer = { version = "0.1.0", path = "../lexer" }
nom = "7.1.3"
num-traits = "0.2.18"
tree = { version = "0.1.0", path = "../tree" }
